/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'referralCode' : IDL.Text,
  'coins' : IDL.Nat,
  'totalEarned' : IDL.Nat,
  'checkInStreak' : IDL.Nat,
  'referredBy' : IDL.Opt(IDL.Text),
  'lastCheckIn' : IDL.Opt(Time),
  'lastSpin' : IDL.Opt(Time),
  'adsWatchedToday' : IDL.Nat,
});
export const TransactionType = IDL.Variant({
  'taskCompletion' : IDL.Null,
  'checkIn' : IDL.Null,
  'adWatch' : IDL.Null,
  'spin' : IDL.Null,
  'referralBonus' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'transactionType' : TransactionType,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveWithdrawal' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'dailyCheckIn' : IDL.Func([], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTopUsers' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getUserTransactions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
  'rejectWithdrawal' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'spinWheel' : IDL.Func([], [IDL.Nat], []),
  'submitWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'watchAd' : IDL.Func([], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'referralCode' : IDL.Text,
    'coins' : IDL.Nat,
    'totalEarned' : IDL.Nat,
    'checkInStreak' : IDL.Nat,
    'referredBy' : IDL.Opt(IDL.Text),
    'lastCheckIn' : IDL.Opt(Time),
    'lastSpin' : IDL.Opt(Time),
    'adsWatchedToday' : IDL.Nat,
  });
  const TransactionType = IDL.Variant({
    'taskCompletion' : IDL.Null,
    'checkIn' : IDL.Null,
    'adWatch' : IDL.Null,
    'spin' : IDL.Null,
    'referralBonus' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'transactionType' : TransactionType,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveWithdrawal' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'dailyCheckIn' : IDL.Func([], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTopUsers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getUserTransactions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
    'rejectWithdrawal' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'spinWheel' : IDL.Func([], [IDL.Nat], []),
    'submitWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'watchAd' : IDL.Func([], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };